# Generated by Django 2.2.4 on 2021-11-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(max_length=1000, verbose_name='Название катеории')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=20, verbose_name='Имейл')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('discription', models.CharField(max_length=1000, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('end_data', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('catalog_data', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='olx.AdvertisementCatalog')),
                ('seller_data', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='olx.AdvertisementSeller')),
            ],
        ),
    ]
